I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name (u'D:\\Dropbox\\RenPy-games\\HSS - revisited/game/screens.rpy', 1513924954, 307) is defined twice, at game/screens.rpy:12 and game/screens (SinderellaV2's conflicted copy 2018-02-01).rpyc:12.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files (x86)\renpy-6.99.13-sdk\renpy\bootstrap.py", line 306, in bootstrap
    renpy.main.main()
  File "C:\Program Files (x86)\renpy-6.99.13-sdk\renpy\main.py", line 367, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Program Files (x86)\renpy-6.99.13-sdk\renpy\script.py", line 266, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Program Files (x86)\renpy-6.99.13-sdk\renpy\script.py", line 757, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn)
  File "C:\Program Files (x86)\renpy-6.99.13-sdk\renpy\script.py", line 423, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'D:\\Dropbox\\RenPy-games\\HSS - revisited/game/screens.rpy', 1513924954, 307) is defined twice, at game/screens.rpy:12 and game/screens (SinderellaV2's conflicted copy 2018-02-01).rpyc:12.

Windows-8-6.2.9200
Ren'Py 6.99.14.1.3198
 
Thu Feb 01 23:26:08 2018
